In [2]:
import pandas as pd
import json

In [3]:
with open("../data/raw/data/events/15946.json", "r") as f:
    data = json.load(f)

events = pd.DataFrame(data)

In [4]:
events.columns

Index(['id', 'index', 'period', 'timestamp', 'minute', 'second', 'type',
       'possession', 'possession_team', 'play_pattern', 'team', 'duration',
       'tactics', 'related_events', 'player', 'position', 'location', 'pass',
       'carry', 'ball_receipt', 'under_pressure', 'duel', 'counterpress',
       'interception', 'off_camera', 'ball_recovery', 'shot', 'goalkeeper',
       'clearance', 'block', 'dribble', 'foul_committed', 'foul_won', 'out',
       'miscontrol', 'bad_behaviour', 'substitution'],
      dtype='object')

In [5]:
events["type"].head()

0    {'id': 35, 'name': 'Starting XI'}
1    {'id': 35, 'name': 'Starting XI'}
2     {'id': 18, 'name': 'Half Start'}
3     {'id': 18, 'name': 'Half Start'}
4           {'id': 30, 'name': 'Pass'}
Name: type, dtype: object

In [6]:
event_types = events["type"].apply(lambda x: x["name"])
event_types

0       Starting XI
1       Starting XI
2        Half Start
3        Half Start
4              Pass
           ...
3757       Pressure
3758           Shot
3759    Goal Keeper
3760       Half End
3761       Half End
Name: type, Length: 3762, dtype: object

In [7]:
event_types.value_counts()

type
Pass              1163
Ball Receipt*     1058
Carry              890
Pressure           212
Ball Recovery       89
Duel                53
Clearance           37
Goal Keeper         34
Block               32
Shot                28
Dribble             24
Interception        24
Foul Committed      23
Dispossessed        21
Foul Won            21
Miscontrol          17
Dribbled Past       14
Substitution         6
Tactical Shift       4
Half Start           4
Half End             4
Starting XI          2
Bad Behaviour        1
Error                1
Name: count, dtype: int64

In [8]:
events["possession_team_name"] = events["possession_team"].apply(lambda x: x["name"])
events["type_name"] = events["type"].apply(lambda x: x["name"])

events[["id", "possession", "possession_team_name", "type_name", "location"]].head()

,id,possession,possession_team_name,type_name,location
0,9f6e2ecf-6685-45df-a62e-c2db3090f6c1,1,Barcelona,Starting XI,NaN
1,0300039d-150d-41e4-b29a-76602ef002e6,1,Barcelona,Starting XI,NaN
2,491e8901-7630-4cc8-b57b-937dddff2eaa,1,Barcelona,Half Start,NaN
3,757b85ad-ddfe-44d5-b893-c23a9fb709d8,1,Barcelona,Half Start,NaN
4,549567bd-36de-4ac8-b8dc-6b5d3f1e4be8,2,Deportivo Alavés,Pass,"[61.0, 40.1]"

Columns needed: 'id', 'index', 'match_id', 'minute', 'second', 'type', 'possession', 'possession_team', 'player', 'location', 
'shot', 'carry', 'duration'. Match id is the name of the json file, in this case, 15946.

In [10]:
events[["id", "possession", "possession_team_name", "type_name", "location", "possession", "player", "location", "shot", "carry", "duration"]].head()

,id,possession,possession_team_name,type_name,location,possession,player,location,shot,carry,duration
0,9f6e2ecf-6685-45df-a62e-c2db3090f6c1,1,Barcelona,Starting XI,NaN,1,NaN,NaN,NaN,NaN,0.000000
1,0300039d-150d-41e4-b29a-76602ef002e6,1,Barcelona,Starting XI,NaN,1,NaN,NaN,NaN,NaN,0.000000
2,491e8901-7630-4cc8-b57b-937dddff2eaa,1,Barcelona,Half Start,NaN,1,NaN,NaN,NaN,NaN,0.000000
3,757b85ad-ddfe-44d5-b893-c23a9fb709d8,1,Barcelona,Half Start,NaN,1,NaN,NaN,NaN,NaN,0.000000
4,549567bd-36de-4ac8-b8dc-6b5d3f1e4be8,2,Deportivo Alavés,Pass,"[61.0, 40.1]",2,"{'id': 6581, 'name': 'Jonathan Rodríguez Menén...","[61.0, 40.1]",NaN,NaN,2.015669